/** What an Alert is about. Its own module so the column's enum and everything that reads it
 *  come from one list. Mirrored in @OpenFarm/domain, which the client reads; the db package
 *  deliberately depends on nothing. */
export const ALERT_KINDS = [
  "instance_overdue",
  "instance_escalated",
  "instance_sent_back",
  "needs_review",
  "sop_published",
  "sop_proposed",
  "sop_retired",
  "sop_restored",
  "withdrawal_ending",
  "notifiable_diagnosis",
  "entry_rejected",
  "withdrawal_changed",
  "low_stock",
  "money_awaiting_approval",
  "registration_renewal_due",
  "investor_statement_due",
  "reimbursement_due",
  "day_not_turning",
  "backup_overdue",
  "lot_expiring",
  "lot_expired",
  "medicine_low_stock",
  "expired_dose_given",
  "join_requested",
  "receivable_overdue",
  "animal_missing",
  "store_shortfall",
  "pen_sores_seen",
  "milk_unaccounted",
  "head_count_differs",
  "dose_not_prescribed",
  "entered_twice",
  "sold_under_cost",
  "still_here_after_eid",
  "medicine_short",
  "feed_price_jump",
  "settings_changed",
  "cash_short",
  "arrival_weight_short",
  "large_shrink",
  "mortality_recorded",
  "mortality_undiagnosed",
  "monthly_sum_missed",
  "pay_in_note_sent",
  "credit_after_write_off",
  "password_guessed",
  "monthly_copy_failed",
  "work_missed",
  "taken_back",
  "proposal_answered",
] as const;
export type AlertKind = (typeof ALERT_KINDS)[number];
